# -*- coding: utf-8 -*-
"""
Curadoria dos candidatos extraidos do texto integral de Montessori.

Duas coisas diferentes, que o site mantem separadas:
  - A CITACAO e um fato: o nome esta na pagina, N vezes, nesta obra. Sai do extrator.
  - A IDENTIFICACAO e um juízo: quem e essa pessoa. Sai daqui, com grau de certeza.

certeza: "alta"    identificação segura (figura conhecida, contexto inequivoco)
         "media"   identificação provavel, coerente com o contexto
         "sobrenome" so o sobrenome e legivel; a citação e real, a pessoa não foi identificada

campo: lente para comparar com Freire -- de que território intelectual vem quem cada um chama.
"""

# nome canonico: (tokens, vida, pais, campo, certeza, nota)
PESSOAS = {
 # ---------------- linhagem pedagógica direta ----------------
 "Édouard Séguin": (["Séguin"], "1812-1880", "FR/EUA", "pedagogia", "alta",
    "Médico-educador de crianças com deficiência intelectual. A fonte declarada do método: Montessori diz ter traduzido a mão suas obras."),
 "Jean Marc Gaspard Itard": (["Itard"], "1774-1838", "FR", "pedagogia", "alta",
    "Médico do 'selvagem de Aveyron'. Com Seguin, o par fundador que ela reivindica."),
 "Friedrich Fröbel": (["Froebel", "Froebelian", "Fraebelius"], "1782-1852", "DE", "pedagogia", "alta",
    "Criador do kindergarten. Citado sobretudo para marcar diferença."),
 "Johann Heinrich Pestalozzi": (["Pestalozzi"], "1746-1827", "CH", "pedagogia", "alta", ""),
 "Jean-Jacques Rousseau": (["Rousseau"], "1712-1778", "CH/FR", "filosofia", "alta", ""),
 "Johann Friedrich Herbart": (["Herbart"], "1776-1841", "DE", "pedagogia", "alta", ""),
 "Édouard Claparède": (["Claparède"], "1873-1940", "CH", "psicologia", "alta", ""),
 "Ernst Meumann": (["Meumann"], "1862-1915", "DE", "pedagogia", "alta", "Pedagogia experimental."),
 "Medard Schuyten": (["Schuyten"], "1866-1948", "BE", "pedagogia", "alta", "Pedologia."),
 "Guy Montrose Whipple": (["Whipple"], "1876-1941", "EUA", "psicologia", "alta", "Manual de testes mentais."),
 "Ugo Pizzoli": (["Pizzoli"], "1863-1934", "IT", "pedagogia", "media", "Pedagogia científica italiana."),
 "Luigi Credaro": (["Credaro"], "1860-1939", "IT", "pedagogia", "media", "Pedagogo e ministro da Instrução."),
 "Émile Jaques-Dalcroze": (["Dalcroze"], "1865-1950", "CH", "arte", "alta", "Rítmica."),
 "Désiré-Magloire Bourneville": (["Bourneville"], "1840-1909", "FR", "medicina", "alta", ""),
 "Félix Voisin": (["Voisin"], "1794-1872", "FR", "medicina", "alta", ""),
 "Jacob Rodrigues Pereire": (["Pereire"], "1715-1780", "PT/FR", "pedagogia", "alta", "Educação de surdos."),
 "Fénelon": (["Fénelon", "Fenelon"], "1651-1715", "FR", "pedagogia", "alta", ""),
 "Francesco Randone": (["Randone"], "1864-1935", "IT", "arte", "media",
    "Artista, 'Escola de Arte Educativa' em Roma; ela adota os exercícios de cerâmica dele."),
 "Lucy Latter": (["Latter"], "?-1917", "GB", "pedagogia", "media", "Jardinagem escolar inglesa."),
 "Anna Maccheroni": (["Maccheroni"], "1876-1965", "IT", "pedagogia", "alta", "Colaboradora direta; música."),
 "Edoardo Talamo": (["Talamo", "Talamo--they"], "1861-1932", "IT", "outros", "alta",
    "Engenheiro do Istituto Romano dei Beni Stabili: quem lhe entrega a primeira Casa dei Bambini."),
 "Mlle. Dufresne": (["Dufresne"], None, "FR/GB", "pedagogia", "sobrenome", "Professora de uma escola do método na Inglaterra."),
 "Helen Parkhurst": (["Parkhurst"], "1887-1973", "EUA", "pedagogia", "media", "Depois criadora do plano Dalton."),
 "Anne Sullivan Macy": (["Sullivan", "Macy"], "1866-1936", "EUA", "pedagogia", "media", "Professora de Helen Keller."),
 "Helen Keller": (["Keller"], "1880-1968", "EUA", "outros", "alta", ""),

 # ---------------- antropologia fisica e antropometria ----------------
 "Giuseppe Sergi": (["Sergi"], "1841-1936", "IT", "antropologia", "alta",
    "Antropólogo, professor dela em Roma. O token 'Sergi' inclui também o filho Sergio Sergi."),
 "Sergio Sergi": (["Sergio"], "1878-1972", "IT", "antropologia", "alta", "Filho de Giuseppe Sergi."),
 "Paul Broca": (["Broca", "Broca'a"], "1824-1880", "FR", "antropologia", "alta", ""),
 "Léonce Manouvrier": (["Manouvrier"], "1850-1927", "FR", "antropologia", "alta", ""),
 "Paul Topinard": (["Topinard"], "1830-1911", "FR", "antropologia", "alta", ""),
 "Joseph Deniker": (["Deniker"], "1852-1918", "FR", "antropologia", "alta", ""),
 "Aleš Hrdlička": (["Hrdlicka"], "1869-1943", "CZ/EUA", "antropologia", "alta", ""),
 "Anders Retzius": (["Retzius"], "1796-1860", "SE", "antropologia", "alta", "Índice cefálico."),
 "Adolphe Quételet": (["Quétélet", "Quetélét"], "1796-1874", "BE", "estatística", "alta",
    "O 'homem médio' e a curva binomial: a matriz estatística da antropologia pedagógica dela."),
 "Ridolfo Livi": (["Livi"], "1856-1920", "IT", "antropologia", "alta", "Antropometria militar italiana."),
 "Luigi Pagliani": (["Pagliani"], "1847-1932", "IT", "medicina", "alta", "Curvas de crescimento infantil."),
 "Paul Godin": (["Godin"], "1860-1935", "FR", "antropologia", "alta", "Auxologia."),
 "Fernando de Helguero": (["Helguero"], "1875-1918", "IT", "estatística", "media", "Curvas de seriação."),
 "René Collignon": (["Collignon"], "1856-1932", "FR", "antropologia", "media", ""),
 "Otto Ammon": (["Ammon"], "1842-1916", "DE", "antropologia", "media", ""),
 "Johann Friedrich Blumenbach": (["Blumenbach"], "1752-1840", "DE", "antropologia", "alta", ""),
 "Petrus Camper": (["Camper"], "1722-1789", "NL", "antropologia", "alta", "Ângulo facial."),
 "Hermann Welcker": (["Welcker"], "1822-1897", "DE", "antropologia", "media", ""),
 "Luigi Calori": (["Calori"], "1807-1896", "IT", "antropologia", "media", ""),
 "Paolo Mantegazza": (["Mantegazza"], "1831-1910", "IT", "antropologia", "alta", ""),
 "Gustave Le Bon": (["Lebon"], "1841-1931", "FR", "antropologia", "media", ""),
 "Carl Heinrich Stratz": (["Stratz"], "1858-1924", "DE", "antropologia", "media", ""),
 "Franz Daffner": (["Daffner"], "1854-1934", "DE", "antropologia", "media", ""),
 "Hermann Vierordt": (["Vierordt"], "1853-1943", "DE", "medicina", "media", ""),
 "Henri Thulié": (["Thulié"], "1832-1916", "FR", "pedagogia", "alta", "'Le dressage des jeunes degeneres'."),
 "Angelo Messedaglia": (["Messedaglia"], "1820-1901", "IT", "estatística", "media", ""),
 "Luigi Bodio": (["Bodio"], "1840-1920", "IT", "estatística", "media", ""),
 "Louis Lapicque": (["Lapique"], "1866-1952", "FR", "biologia", "media", ""),
 "Karl Pearson": (["Pearson"], "1857-1936", "GB", "estatística", "alta", "Biometria."),
 "Wilhelm Lexis": (["Lexis"], "1837-1914", "DE", "estatística", "media", ""),
 "Robert Boyd": (["Boyd"], "1808-1883", "GB", "medicina", "media", "Pesos de órgãos e encéfalo."),
 "Bonnifay": (["Bonnifay"], None, "FR", "antropologia", "sobrenome", "Citado sobre desenvolvimento cefálico."),
 "Moige": (["Moige"], None, "FR", "medicina", "sobrenome", "Citado da 'Nouvelle Iconographie de la Salpetriere'."),
 "Eugène Apert": (["Apert"], "1868-1940", "FR", "medicina", "media", ""),

 # ---------------- biologia, hereditariedade, evolucao ----------------
 "Gregor Mendel": (["Mendel", "Mendelism"], "1822-1884", "AT", "biologia", "alta",
    "As leis de Mendel entram na 'Antropologia Pedagógica' como base da hereditariedade."),
 "Hugo de Vries": (["Vries"], "1848-1935", "NL", "biologia", "alta", ""),
 "Carl Correns": (["Correns"], "1864-1933", "DE", "biologia", "alta", ""),
 "Erich von Tschermak": (["Tschermack"], "1871-1962", "AT", "biologia", "alta", ""),
 "William Bateson": (["Bateson"], "1861-1926", "GB", "biologia", "alta", ""),
 "Arthur Darbishire": (["Darbishire"], "1879-1915", "GB", "biologia", "media", ""),
 "Lucien Cuénot": (["Cuénot"], "1866-1951", "FR", "biologia", "alta", ""),
 "Charles Davenport": (["Davenport"], "1866-1944", "EUA", "biologia", "alta", "Eugenia."),
 "Carl von Nägeli": (["Naegeli"], "1817-1891", "CH", "biologia", "alta", ""),
 "Charles Darwin": (["Darwin", "Darwinism"], "1809-1882", "GB", "biologia", "alta", ""),
 "Jean-Baptiste Lamarck": (["Lamarck"], "1744-1829", "FR", "biologia", "alta", ""),
 "Ernst Haeckel": (["Haeckel", "Anthropogenie"], "1834-1919", "DE", "biologia", "alta", ""),
 "Thomas Henry Huxley": (["Huxley"], "1825-1895", "GB", "biologia", "alta", ""),
 "Georges Cuvier": (["Cuvier"], "1769-1832", "FR", "biologia", "alta", ""),
 "Carl von Linné": (["Linnaeus"], "1707-1778", "SE", "biologia", "alta", ""),
 "Buffon": (["Buffon"], "1707-1788", "FR", "biologia", "alta", ""),
 "Étienne Geoffroy Saint-Hilaire": (["Hilaire"], "1772-1844", "FR", "biologia", "media", ""),
 "Johann Friedrich Meckel": (["Meckel"], "1781-1833", "DE", "biologia", "media", ""),
 "Ludwig Rütimeyer": (["Rütimeyer"], "1825-1895", "CH", "biologia", "media", ""),
 "Eugène Dubois": (["Dubois", "Pithecanthropus"], "1858-1940", "NL", "antropologia", "alta", "Pithecanthropus erectus."),
 "Edmond Perrier": (["Perrier"], "1844-1921", "FR", "biologia", "alta", ""),
 "Charles Richet": (["Richet"], "1850-1935", "FR", "medicina", "alta", ""),
 "Claude Bernard": (["Bernard"], "1813-1878", "FR", "medicina", "alta", "'Lecons sur les phenomenes de la vie'."),
 "Max Verworn": (["Verworn"], "1863-1921", "DE", "biologia", "media", ""),
 "Louis Laloy": (["Laloy"], "1874-1944", "FR", "biologia", "media", "Citado sobre a definicao de vida."),
 "Carl Ludwig": (["Ludwig"], "1816-1895", "DE", "medicina", "media", "Fisiologia; teoria das enzimas."),

 # ---------------- medicina, psiquiatria, criminologia ----------------
 "Philippe Pinel": (["Pinel"], "1745-1826", "FR", "medicina", "alta", ""),
 "Bénédict Augustin Morel": (["Morel"], "1809-1873", "FR", "medicina", "alta", "Teoria da degenerescência."),
 "Cesare Lombroso": (["Lombroso", "Lombrosian"], "1835-1909", "IT", "antropologia", "alta",
    "Antropologia criminal. Presença constante e ambivalente na obra dela."),
 "Enrico Ferri": (["Ferri"], "1856-1929", "IT", "outros", "media", "Criminologia e socialismo."),
 "Lino Ferriani": (["Ferriani"], "1852-1921", "IT", "outros", "media", ""),
 "Alfredo Niceforo": (["Niceforo"], "1876-1960", "IT", "antropologia", "alta", "'Les classes pauvres'."),
 "Antonio Marro": (["Marro"], "1840-1913", "IT", "medicina", "alta", "'La puberdade'."),
 "Sante De Sanctis": (["Sanctis", "Sante"], "1862-1935", "IT", "psicologia", "alta",
    "Psiquiatra romano; com ele ela trabalha nas crianças 'anormais'."),
 "Enrico Morselli": (["Morselli"], "1852-1929", "IT", "medicina", "alta", ""),
 "Achille De Giovanni": (["Giovanni"], "1838-1916", "IT", "medicina", "alta", "Clínica morfológica; base da tipologia dela."),
 "Giacinto Viola": (["Viola"], "1870-1943", "IT", "medicina", "alta", "'Homem medial'; discípulo de De Giovanni."),
 "Raffaele Brugia": (["Brugia"], "1859-1944", "IT", "medicina", "media", ""),
 "Boxich": (["Boxich"], None, "IT", "medicina", "sobrenome", "Aplica o método de De Giovanni a criminosos."),
 "Massini": (["Massini"], None, "IT", "medicina", "sobrenome", "Citado sobre peso do encéfalo."),
 "Vitale Vitali": (["Vitali", "Vitale"], "1854-1930", "IT", "antropologia", "media", "Desenvolvimento da fronte em escolares."),
 "Angelo Mosso": (["Mosso"], "1846-1910", "IT", "medicina", "alta", "Fadiga; ergógrafo."),
 "Alphonse Laveran": (["Laveran"], "1845-1922", "FR", "medicina", "alta", "Parasita da malária; Nobel 1907."),
 "Angelo Celli": (["Celli"], "1857-1914", "IT", "medicina", "alta", "Malaria no Agro Romano."),
 "Ronald Ross": (["Ross"], "1857-1932", "GB", "medicina", "alta", "Transmissão da malária; Nobel 1902."),
 "Élie Metchnikoff": (["Metchnikoff"], "1845-1916", "RU/FR", "biologia", "alta", ""),
 "Adolf Kussmaul": (["Kussmaul"], "1822-1902", "DE", "medicina", "alta", ""),
 "Carl Wernicke": (["Wernicke"], "1848-1905", "DE", "medicina", "alta", ""),
 "Xavier Bichat": (["Bichat"], "1771-1802", "FR", "medicina", "alta", ""),
 "Marcello Malpighi": (["Malpighi", "Malpighian"], "1628-1694", "IT", "medicina", "alta", ""),
 "William Harvey": (["Harvey"], "1578-1657", "GB", "medicina", "alta", ""),
 "Girolamo Fabrici d'Acquapendente": (["Fabricius"], "1533-1619", "IT", "medicina", "alta", ""),
 "Antonie van Leeuwenhoek": (["Leuwenhoek"], "1632-1723", "NL", "biologia", "alta", ""),
 "Jan Evangelista Purkinje": (["Purkinje"], "1787-1869", "CZ", "medicina", "alta", ""),
 "Rudolf Virchow": (["Virchow"], "1821-1902", "DE", "medicina", "alta", ""),
 "Jacob Moleschott": (["Moleschott"], "1822-1893", "NL/IT", "medicina", "alta", ""),
 "Adolphe Pinard": (["Pinard"], "1844-1934", "FR", "medicina", "alta", "Puericultura."),
 "Charles Féré": (["Féré"], "1852-1907", "FR", "medicina", "alta", ""),
 "Moritz Benedikt": (["Benedickt"], "1835-1920", "AT", "medicina", "media", ""),
 "Charles Lasègue": (["Lasegue"], "1816-1883", "FR", "medicina", "media", ""),
 "Louis-Francisque Lelut": (["Lelut"], "1804-1877", "FR", "medicina", "media", ""),
 "Maximien Parchappe": (["Parchappe"], "1800-1866", "FR", "medicina", "media", ""),
 "Hermann Wildermuth": (["Wildermuth"], "1852-1907", "DE", "medicina", "media", ""),
 "Walter E. Fernald": (["Fernald"], "1859-1924", "EUA", "medicina", "media", ""),
 "Paul Tillaux": (["Tillaux"], "1834-1904", "FR", "medicina", "media", ""),
 "Guido Baccelli": (["Baccelli"], "1830-1916", "IT", "medicina", "media", ""),
 "Bartolomeo Gosio": (["Gosio"], "1863-1944", "IT", "medicina", "media", ""),
 "Franz von Winckel": (["Winckel"], "1837-1911", "DE", "medicina", "media", ""),
 "Eugène Hertoghe": (["Hertoghe"], "1860-1928", "BE", "medicina", "media", ""),
 "Luigi Luciani": (["Luciani"], "1840-1919", "IT", "medicina", "media", ""),
 "Figueira": (["Figueira"], None, "BR", "medicina", "sobrenome",
    "Citado do Rio de Janeiro, 'Semejotica Infantile'. A única referência brasileira que o corpus devolve."),

 # ---------------- psicologia experimental ----------------
 "Wilhelm Wundt": (["Wundt"], "1832-1920", "DE", "psicologia", "alta", ""),
 "Alfred Binet": (["Binet"], "1857-1911", "FR", "psicologia", "alta", "Escala métrica da inteligência."),
 "Théodore Simon": (["Simon"], "1873-1961", "FR", "psicologia", "media", "Coautor da escala Binet-Simon."),
 "Gustav Fechner": (["Fechner"], "1801-1887", "DE", "psicologia", "alta", "Psicofísica."),
 "Ernst Heinrich Weber": (["Weber"], "1795-1878", "DE", "psicologia", "media", ""),
 "William Preyer": (["Preyer"], "1841-1897", "DE", "psicologia", "alta", "'A alma da criança'."),
 "William James": (["James"], "1842-1910", "EUA", "psicologia", "alta", ""),
 "Alexander Bain": (["Bain"], "1818-1903", "GB", "psicologia", "media", ""),
 "Edward Wheeler Scripture": (["Scripture"], "1864-1945", "EUA", "psicologia", "media", ""),

 # ---------------- filosofia ----------------
 "Immanuel Kant": (["Kant"], "1724-1804", "DE", "filosofia", "alta", ""),
 "Friedrich Nietzsche": (["Nietzsche"], "1844-1900", "DE", "filosofia", "alta", ""),
 "Herbert Spencer": (["Spencer"], "1820-1903", "GB", "filosofia", "alta", ""),
 "John Stuart Mill": (["Mill"], "1806-1873", "GB", "filosofia", "media", ""),
 "Roberto Ardigò": (["Ardigo"], "1828-1920", "IT", "filosofia", "alta", "Positivismo italiano."),
 "Gottfried Wilhelm Leibniz": (["Liebnitz"], "1646-1716", "DE", "filosofia", "alta", ""),
 "Aristóteles": (["Aristotle"], "384-322 a.C.", "GR", "filosofia", "alta", ""),
 "Pitágoras": (["Pythagoras"], "c.570-495 a.C.", "GR", "filosofia", "alta", ""),
 "Voltaire": (["Voltaire"], "1694-1778", "FR", "filosofia", "alta", ""),
 "Erminio Troilo": (["Troilo"], "1874-1968", "IT", "filosofia", "media", ""),
 "Gabriel Tarde": (["Tarde"], "1843-1904", "FR", "outros", "media", ""),
 "Edvard Westermarck": (["Westermarck"], "1862-1939", "FI", "outros", "media", ""),

 # ---------------- ciencia ----------------
 "Galileu Galilei": (["Galilei", "Galileo"], "1564-1642", "IT", "ciencia", "alta", ""),
 "Isaac Newton": (["Newton"], "1643-1727", "GB", "ciencia", "alta", ""),
 "Arquimedes": (["Archimedes"], "c.287-212 a.C.", "GR", "ciencia", "alta", ""),
 "Alessandro Volta": (["Volta"], "1745-1827", "IT", "ciencia", "alta", ""),
 "Guglielmo Marconi": (["Marconi"], "1874-1937", "IT", "ciencia", "alta", ""),
 "Denis Papin": (["Papin"], "1647-1713", "FR", "ciencia", "media", ""),
 "Carlo Matteucci": (["Matteucci"], "1811-1868", "IT", "ciencia", "media", ""),
 "Vitrúvio": (["Vitruvius"], "c.80-15 a.C.", "IT", "ciencia", "alta", ""),
 "Hipócrates": (["Hippocrates"], "c.460-370 a.C.", "GR", "medicina", "alta", ""),
 "Galeno": (["Galen"], "129-c.216", "GR", "medicina", "alta", ""),
 "Heródoto": (["Herodotus"], "c.484-425 a.C.", "GR", "história", "alta", ""),

 # ---------------- literatura ----------------
 "Dante Alighieri": (["Dante", "Alighieri"], "1265-1321", "IT", "literatura", "alta",
    "A referência literária mais presente; a 'Divina Comédia' aparece como material de leitura."),
 "Alessandro Manzoni": (["Manzoni"], "1785-1873", "IT", "literatura", "alta", ""),
 "Giacomo Leopardi": (["Leopardi"], "1798-1837", "IT", "literatura", "alta", ""),
 "Giosuè Carducci": (["Carducci"], "1835-1907", "IT", "literatura", "alta", ""),
 "Vittorio Alfieri": (["Alfieri"], "1749-1803", "IT", "literatura", "alta", ""),
 "Metastasio": (["Metastasio"], "1698-1782", "IT", "literatura", "alta", ""),
 "Giovanni Prati": (["Prati"], "1814-1884", "IT", "literatura", "alta", ""),
 "Giacomo Zanella": (["Zanella"], "1820-1888", "IT", "literatura", "alta", ""),
 "Paolo Rolli": (["Rolli"], "1687-1765", "IT", "literatura", "media", ""),
 "Guido Mazzoni": (["Mazzoni"], "1859-1943", "IT", "literatura", "media", ""),
 "Felice Cavallotti": (["Cavallotti"], "1842-1898", "IT", "literatura", "media", ""),
 "William Shakespeare": (["Shakespeare"], "1564-1616", "GB", "literatura", "alta", ""),
 "John Milton": (["Milton"], "1608-1674", "GB", "literatura", "alta", ""),
 "William Wordsworth": (["Wordsworth"], "1770-1850", "GB", "literatura", "alta", ""),
 "Lord Byron": (["Byron"], "1788-1824", "GB", "literatura", "alta", ""),
 "Alfred Tennyson": (["Tennyson"], "1809-1892", "GB", "literatura", "alta", ""),
 "Henry Wadsworth Longfellow": (["Longfellow"], "1807-1882", "EUA", "literatura", "alta", ""),
 "Robert Browning": (["Browning"], "1812-1889", "GB", "literatura", "alta", ""),
 "Algernon Swinburne": (["Swinburne"], "1837-1909", "GB", "literatura", "alta", ""),
 "Walter Scott": (["Scott", "Waverley"], "1771-1832", "GB", "literatura", "alta", ""),
 "Samuel Taylor Coleridge": (["Coleridge"], "1772-1834", "GB", "literatura", "alta", ""),
 "Percy Bysshe Shelley": (["Shelley"], "1792-1822", "GB", "literatura", "alta", ""),
 "Rudyard Kipling": (["Kipling"], "1865-1936", "GB", "literatura", "alta", ""),
 "Edgar Allan Poe": (["Poe"], "1809-1849", "EUA", "literatura", "alta", ""),
 "Oliver Goldsmith": (["Goldsmith"], "1728-1774", "IE/GB", "literatura", "alta", ""),
 "William Cullen Bryant": (["Bryant"], "1794-1878", "EUA", "literatura", "media", ""),
 "John Dryden": (["Dryden"], "1631-1700", "GB", "literatura", "alta", ""),
 "Robert Herrick": (["Herrick"], "1591-1674", "GB", "literatura", "media", ""),
 "Joseph Addison": (["Addison"], "1672-1719", "GB", "literatura", "media", ""),
 "Robert Burns": (["Burns"], "1759-1796", "GB", "literatura", "media", ""),
 "Julia Ward Howe": (["Howe"], "1819-1910", "EUA", "literatura", "media", "'Battle Hymn of the Republic', citado como exemplo métrico."),
 "Henry Francis Cary": (["Carey"], "1772-1844", "GB", "literatura", "media", "Tradutor inglês de Dante citado nas passagens da 'Comédia'."),
 "William Webbe": (["Webbe"], "c.1550-1591", "GB", "literatura", "media", ""),
 "Johann Wolfgang von Goethe": (["Goethe", "Faust"], "1749-1832", "DE", "literatura", "alta", ""),
 "Friedrich Schiller": (["Schiller"], "1759-1805", "DE", "literatura", "alta", ""),
 "Liev Tolstói": (["Tolstoy"], "1828-1910", "RU", "literatura", "alta", ""),
 "George Eliot": (["Eliot", "Marner"], "1819-1880", "GB", "literatura", "alta", ""),
 "Homero": (["Homer"], "sec. VIII a.C.", "GR", "literatura", "alta", ""),
 "Virgílio": (["Virgil"], "70-19 a.C.", "IT", "literatura", "alta", ""),
 "Charles de Montalembert": (["Montalembert"], "1810-1870", "FR", "história", "media", ""),
 "Nahum Tate": (["Tate"], "1652-1715", "IE/GB", "literatura", "media", ""),

 # ---------------- arte e música ----------------
 "Michelangelo": (["Michelangelo"], "1475-1564", "IT", "arte", "alta", ""),
 "Rafael Sanzio": (["Raphael", "Sanzio", "Fornarina"], "1483-1520", "IT", "arte", "alta", ""),
 "Giotto": (["Giotto"], "c.1267-1337", "IT", "arte", "alta", ""),
 "Sandro Botticelli": (["Botticelli"], "1445-1510", "IT", "arte", "alta", ""),
 "Giovanni Bellini": (["Bellini"], "c.1430-1516", "IT", "arte", "media", ""),
 "Paolo Veronese": (["Veronese"], "1528-1588", "IT", "arte", "media", ""),
 "Peter Paul Rubens": (["Rubens"], "1577-1640", "BE", "arte", "alta", ""),
 "Fídias": (["Phidias"], "c.480-430 a.C.", "GR", "arte", "alta", ""),
 "Ludwig van Beethoven": (["Beethoven"], "1770-1827", "DE", "arte", "alta", ""),
 "Richard Wagner": (["Wagner", "Parsifal"], "1813-1883", "DE", "arte", "alta", ""),
 "Frédéric Chopin": (["Chopin"], "1810-1849", "PL", "arte", "alta", ""),

 # ---------------- so aparecem no aparato de referência formal ----------------
 "Gaetano Pieraccini": (["Pieraccini"], "1864-1957", "IT", "medicina", "media", "Medicina do trabalho e patologia social."),
 "Angelo Zanolli": (["Zanolli"], None, "IT", "medicina", "sobrenome", ""),
 "Achille Sclavo": (["Sclavo"], "1861-1930", "IT", "medicina", "media", ""),

 # ---------------- história e religiao ----------------
 "Napoleão Bonaparte": (["Napoleon", "Bonaparte"], "1769-1821", "FR", "história", "alta", ""),
 "Giuseppe Garibaldi": (["Garibaldi"], "1807-1882", "IT", "história", "alta", ""),
 "Cristóvão Colombo": (["Columbus"], "1451-1506", "IT", "história", "alta", ""),
 "Oliver Cromwell": (["Cromwell"], "1599-1658", "GB", "história", "media", ""),
 "Lucrécia Bórgia": (["Borgia", "Lucrezia"], "1480-1519", "IT", "história", "media", ""),
 "Teresa de Ávila": (["Teresa"], "1515-1582", "ES", "religiao", "media", ""),
 "João Crisóstomo": (["Chrysostom", "Chrisostom"], "c.347-407", "GR", "religiao", "media", ""),
 "São Francisco de Assis": (["Francis"], "1181-1226", "IT", "religiao", "media", ""),
}

# Tokens que o extrator devolve mas NAO são citação de pessoa. Ficam registrados
# para que a exclusão seja auditável, e não um silêncio.
EXCLUIDOS = {
 "Alicia": "revisora do Project Gutenberg (créditos da digitalização)",
 "Williams": "revisora do Project Gutenberg",
 "Brenda": "revisora do Project Gutenberg",
 "Lewis": "revisor do Project Gutenberg",
 "Carl": "'Copyright 1912 by Carl R. Byoir' -- crédito fotográfico",
 "Byoir": "crédito fotográfico das fotos do livro",
 "Tara": "'Tara's halls', verso de Thomas Moore -- topônimo",
 "Hoepli": "Ulrico Hoepli, editora",
 "Montessori": "a própria autora",
 "Maria": "prenome da autora e nome de criança nos exemplos",
 "George": "Anne E. George, tradutora do livro para o inglês",
 "Mary": "nome de criança nos exercícios de gramática",
 "Paul": "'Paul Revere' nos exercícios de leitura",
 "Hilany": "Hilany Agyba, caso clínico descrito -- não e autora citada",
}
